* org-export-todoist.el

[[https://github.com/MasWag/org-export-todoist/actions/workflows/unit_test.yml][https://github.com/MasWag/org-export-todoist/actions/workflows/unit_test.yml/badge.svg?branch=master]]
[[./LICENSE][https://img.shields.io/badge/License-GPLv3-blue.svg]]

An Emacs Lisp function to push tasks of org-agenda as tasks of [[https://todoist.com/][todoist]].

** Dependencies

- =ox-icalendar.el=
  - =ox-icalendar.el= is part of GNU Emacs.
- [[https://github.com/abrochard/emacs-todoist][todoist.el]]
  - You can install via melpa.

** Installation

- Download =org-export-todoist.el= and run =(load-file "/path/to/org-export-todoist.el")=
- Or, place =org-export-todoist.el= to somewhere suitable and run =(require 'org-export-todoist)=.

** Usage

1. =M-x org-agenda= to open a list of agenda
2. =M-x org-current-agenda-export-todoist= to export the current tasks.

** Note

This is, at least currently, my very personal project, and I have no plan to implement/test any features beyond my personal usage. Nevertheless, any improvement or feedback (via GitHub Issues and/or Pull Request) is welcome.

** Unit Test

Unit test can be run as follows.

#+BEGIN_SRC sh
  emacs -Q --batch  -L . --eval "(package-initialize)" --eval "(package-install 'todoist)" -l ./test-org-export-todoist.el --eval '(setq ert-batch-backtrace-right-margin 100)'  --eval '(ert-run-tests-batch-and-exit (quote t))'
#+END_SRC
