name: Unit Test

on:
  push:
    branches:
      - master

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y emacs

    - name: Run unit test
      run: |
        emacs -Q --batch  -L . --eval "(require 'package)"  --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\"))" --eval '(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")' --eval "(package-initialize)" --eval "(package-refresh-contents)" --eval "(package-install 'todoist)" -l ./test-org-export-todoist.el --eval '(setq ert-batch-backtrace-right-margin 100)'  --eval '(ert-run-tests-batch-and-exit (quote t))'
