name: Unit Test

on:
  push:
    branches:
      - master

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y emacs

    - name: Run unit test
      run: |
        emacs -Q --batch  -L . --eval "(package-initialize)" --eval "(package-install 'todoist)" -l ./test-todoist-org-export.el --eval '(setq ert-batch-backtrace-right-margin 100)'  --eval '(ert-run-tests-batch-and-exit (quote t))'
